import Layout from '@/components/Layout'
import Head from 'next/head'
import Image from 'next/image'
import profilePic from '../../public/images/profile/developer-pic-1.png'
import AnimatedText from '@/components/AnimatedText'

export default function Home() {
  return (
    <>
      <Head>
        <title>Redolf Kwame Osei</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      {/* Main Section with Profile Picture and Text.  */}
      <main className='flex items-center text-dark w-full min-h-screen'>
        <Layout className='pt-0'>
          <div className="flex items-center justify-between w-full">

          {/* Profile Picture Section */}
            <div className='w-1/2'>
              <Image src={profilePic} alt='redolfkwameosei' className='w-full h-auto' />
            </div>

            {/* Text Section */}
            <div className='w-1/2'>
              <AnimatedText text="Translate imagination Into Reality With Code And Design"/>
              <p>
              As a skilled full-stack developer, I am dedicated to turning ideas into innovative web applications. 
              Explore my latest projects and articles, showcasing my expertise in React.js and web development.
              </p>
            </div>
          </div>
        </Layout>

      </main>
    </>
  )
}
