import Layout from '@/components/Layout'
import Head from 'next/head'
import Image from 'next/image'
import profilePic from '../../public/images/profile/developer-pic-1.png'
import AnimatedText from '@/components/AnimatedText'
import Link from 'next/link'
import { LinkArrow } from '@/components/Icons'
import HireMe from '@/components/HireMe'
import lightBulb from "../../public/images/svgs/miscellaneous_icons_1.svg"


export default function Home() {
  return (
    <>
      <Head>
        <title>Redolf Kwame Osei</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      {/* Main Section with Profile Picture and Text.  */}
      <main className='flex items-center text-dark w-full min-h-screen'>
        <Layout className='pt-0'>
          <div className="flex items-center justify-between w-full">

          {/* Profile Picture Section */}
            <div className='w-1/2'>
              <Image src={profilePic} alt='redolfkwameosei' className='w-full h-auto' />
            </div>

            {/* Text Section */}
            <div className='w-1/2 flex flex-col items-center self-center'>
              <AnimatedText text="Convert Vision Into Reality With Design And Code" className='!text-6xl !text-left'/>
              <p className='my-4 text-base font-medium'>
              As a skilled full-stack developer, I am dedicated to turning ideas into innovative web applications. 
              Explore my latest projects and articles, showcasing my expertise in React.js and web development.
              </p>

              <div className='flex items-center self-start mt-2'>
                <Link href="/dummy.pdf" target={'_blank'}
                className='flex items-center bg-dark text-light p-2.5 px-6 rounded-lg text-lg font-semibold
                hover:bg-light hover:text-dark border-2 border-solid border-transparent hover:border-dark'
                download={true} >Resume <LinkArrow className={"w-6 ml-1"} /> </Link>
                <Link href="mailto:redolf639@gmail" target={'_blank'}
                className='ml-4 text-lg font-medium capitalize text-dark underline'
                >Contact</Link>
              </div>
            </div>
          </div>
        </Layout>

        <HireMe />

        <div className='absolute right-8 bottom-8 inline-block w-24 '>
          <Image src={lightBulb} alt="redolf kwame osei" className='w-full h-auto'></Image>
        </div>

      </main>
    </>
  )
}
